### ISSUE TITLE
Transfer Sed tanks

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara/aide_featurescript#1]

**Comment by monroews** [comment]
Use this [colab sheet](https://colab.research.google.com/github/AguaClara/CEE4520/blob/master/Unit_Process_Designs/Sed.ipynb) for the sed tank

Use the [AguaClara design code](https://github.com/AguaClara/aguaclara/blob/master/aguaclara/design/sed_chan.py) for the sed channels.

The sedimentor code is not ready to be implemented and we need to determine what is needed.
