### ISSUE TITLE
Refactor Pipeline to use the configurable Pipe library

### ISSUE THREAD

**Issue by oliver-leung** [AguaClara/aide_featurescript#25]

**Comment by oliver-leung** [comment]
@ethan92429 @Emily-Wood This is essentially what you guys did with making the pipes/fittings data-driven, right? If so, I can close this

**Comment by eak24** [comment]
Yup! Here is the link: https://cad.onshape.com/documents/89bad90758e5bb705cfe2c7f/w/38348e7177e8d93d42a16c69/e/c6f4ab81bae6bdf33b135fbb
