### ISSUE TITLE
ENH:

### ISSUE THREAD

**Issue by mc2259** [AguaClara/aide_featurescript#39]
## Use Case
*Improve the functionality of the Tester feature by testing the test functions*

## Solution
*1. Create a Part studio and instantiate different cases of the Tester feature
  2. Perform simple value checks.
  3. Perform unit checks-For eg. checking that 5m not equal to 5 cm.
*

## Alternatives
*This is a part of #35*

**Comment by oliver-leung** [comment]
@mc2259 Thank you for making this issue, but I'm going to close this because it's already covered by the task described in #35. In general, try to avoid making extra issues for the same task, so we don't have to check multiple spots :)
